#!/bin/bash

test -z $1 > /dev/null
if [ $? -eq 0  ]; then
    echo 'Usage:

      ./dockergo [local munin node NAME]
        '
          exit 0
        fi

cat docker-compose.yml | sed -e "s;munin-node$;$1;g" -e "s;munin-node:$;$1:;g" -e "s;munin-node:munin-node;$1:$1;g" > q; mv q docker-compose.yml
docker-compose rm -f ; docker-compose up  &
