#!/bin/bash

test -z $1 > /dev/null
if [ $? -eq 0  ]; then
    echo 'Usage:

      ./dockergo [your local node name e.g. C] '[NODES e.g. a:1.1.1.1 b.2.2.2.2]' [GROUP NAME]
        '
          exit 0
        fi

cat docker-compose.yml | sed -e "s;munin-node$;$1;g" -e "s;munin-node:$;$1:;g" -e "s;munin-node:munin-node;$1:$1;g" -e "s;PERF\";$3\;\";g"  | sed -e "s;\"$1:$1\";\"$1:$1 $2\";g" > q; mv q docker-compose.yml
docker-compose stop && docker-compose rm -f ; docker-compose up  &
